# Generated by Django 2.0.4 on 2018-04-17 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('roll', models.CharField(max_length=10)),
                ('phone', models.IntegerField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('statement_of_purpose', models.CharField(max_length=5000)),
                ('resume_link', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('location', models.CharField(max_length=50)),
                ('no_of_position', models.IntegerField()),
                ('stipend', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
    ]
